services:
  shlink_web_client_node:
    container_name: shlink_web_client_node
    image: node:22.3-alpine
    command: /bin/sh -c "cd /home/shlink/www && npm install && npm run start"
    volumes:
      - ./:/home/shlink/www
    ports:
      - "3000:3000"
      - "56745:56745"
      - "4173:4173"
